apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-golang
  namespace: cicd
spec:
  workspaces:
  - name: workdir
  params:
  - name: version
    description: golang version to use for builds
    default: "latest"
  - name: flags
    description: flags to use for the test command
    default: -v
  - name: GOOS
    description: "running program's operating system target"
    default: linux
  - name: GOARCH
    description: "running program's architecture target"
    default: amd64
  - name: GO111MODULE
    description: "value of module support"
    default: auto
  - name: GOCACHE
    description: "Go caching directory path"
    default: ""
  - name: GOMODCACHE
    description: "Go mod caching directory path"
    default: ""
  steps:
  - name: execute-build
    image: docker.io/library/golang:$(params.version)
    workingdir: $(workspaces.workdir.path)/src
    script: |
      #!/usr/bin/env sh
      sh -xe build.sh
    env:
    - name: GOOS
      value: "$(params.GOOS)"
    - name: GOARCH
      value: "$(params.GOARCH)"
    - name: GO111MODULE
      value: "$(params.GO111MODULE)"
    - name: GOCACHE
      value: "$(params.GOCACHE)"
    - name: GOMODCACHE
      value: "$(params.GOMODCACHE)"
