---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-basic-auth
  namespace: cicd
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://gitlab.linoproject.lab"]
      helper = store
  .git-credentials: |
    https://manuel:password@gitlab.linoproject.lab
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-api-creds
  namespace: cicd
type: Opaque
stringData:
  token: token
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-docker-basic-auth
  namespace: cicd
type: Opaque
stringData:
  config.json: |
    {
      "auths": {
        "https://harbor.linoproject.lab": {
          "username": "manuel",
          "password": "token",
          "auth":"Cg==",
          "email":"not@val.id"
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-helm-basic-auth
  namespace: cicd
type: Opaque
stringData:
  username: manuel
  password: password
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-webhook-token
  namespace: cicd
type: Opaque
stringData:
  token: token
