apiVersion: v1
kind: Secret
metadata:
  name: harbor
  namespace: myteam-myapp-dev
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://harbor.linoproject.lab": {
          "username": "manuel",
          "password": "password",
          "auth":"Cg==",
          "email":"not@val.id"
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor
  namespace: myteam-myapp-prod
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://harbor.linoproject.lab": {
          "username": "manuel",
          "password": "password",
          "auth":"Cg==",
          "email":"not@val.id"
        }
      }
    }
