apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: myteam-myapp-cicd-prod
  namespace: flux-system
spec:
  interval: 1m
  url: https://gitlab.linoproject.lab/myteam/myapp/cicd
  ref:
    branch: prod
  secretRef:
    name: gitlab-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: myteam-myapp-cicd-prod
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: myteam-myapp-cicd-prod
